pipeline {
  agent { 
    dockerfile { filename 'jenkins/masterdata/Dockerfile' }
  }
  environment {
      MY_TOKEN = credentials('TOKEN')
  }
  stages {
    stage('Test') {
      steps {
        withCredentials([usernamePassword(credentialsId: '055build', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
          sh 'python jenkins/masterdata/reconstruct_before.py ${MY_TOKEN} ${scriptId} ${releaseVersion} ${folderName}'
          sh 'python jenkins/masterdata/reconstruct_after.py ${MY_TOKEN} ${scriptId} ${folderName}'
          sh 'python jenkins/masterdata/pull_and_rmdir.py'
          sh 'python jenkins/masterdata/sheet_work_download.py ${MY_TOKEN}'
          sh 'python jenkins/masterdata/push_sheet_work.py'
        }
      }
    }
  }
}